# LifeDJIK: file generated by mkvendor.sh
USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/unknown/m805_892x/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi
TARGET_BOOTLOADER_BOARD_NAME := m805_892x

BOARD_KERNEL_CMDLINE := console=ttyTCC0,115200n8 androidboot.console=ttyTCC0
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 4096

# LifeDJIK: /proc/mtd from my device
#dev:    size   erasesize  name
#mtd0: 00a00000 00100000 "boot"
#mtd1: 00500000 00100000 "kpanic"
#mtd2: 12c00000 00100000 "system"
#mtd3: 00400000 00100000 "splash"
#mtd4: 09600000 00100000 "cache"
#mtd5: 3fe00000 00100000 "userdata"
#mtd6: 00a00000 00100000 "recovery"
#mtd7: 00200000 00100000 "misc"
#mtd8: 00200000 00100000 "tcc"
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00a00000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00a00000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x12c00000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x3fe00000
BOARD_FLASH_BLOCK_SIZE := 1048576

TARGET_PREBUILT_KERNEL := kernel/unknown/m805_892x/prebuilt

BOARD_HAS_NO_SELECT_BUTTON := true

# Use this flag if the board has a ext4 partition larger than 2gb
#BOARD_HAS_LARGE_FILESYSTEM := true
